/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1ed",
        "surface-container": "#ffe9e3",
        "surface-container-high": "#f9e4de",
        "surface-container-highest": "#f3ded8",
        "surface": "#fff8f6",
        "surface-dim": "#ead6d0",
        "surface-bright": "#fff8f6",
        "surface-variant": "#f3ded8",
        "surface-tint": "#a23e18",
        "on-surface": "#241916",
        "on-surface-variant": "#57423b",
        "inverse-surface": "#3a2e2a",
        "inverse-on-surface": "#ffede8",
        "outline": "#8a726a",
        "outline-variant": "#dec0b7",
        "primary": "#9f3c16",
        "on-primary": "#ffffff",
        "primary-container": "#bf542c",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbcf",
        "primary-fixed-dim": "#ffb59c",
        "on-primary-fixed": "#390c00",
        "on-primary-fixed-variant": "#822801",
        "inverse-primary": "#ffb59c",
        "secondary": "#3f5f92",
        "on-secondary": "#ffffff",
        "secondary-container": "#a5c5fe",
        "on-secondary-container": "#305183",
        "secondary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#a9c7ff",
        "on-secondary-fixed": "#001b3d",
        "on-secondary-fixed-variant": "#254778",
        "tertiary": "#7b542b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#966c41",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdcbd",
        "tertiary-fixed-dim": "#f0bd8b",
        "on-tertiary-fixed": "#2c1600",
        "on-tertiary-fixed-variant": "#623f18",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fff8f6",
        "on-background": "#241916",
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'warm-sm': '0 2px 8px rgba(159, 60, 22, 0.05)',
        'warm': '0 4px 20px rgba(159, 60, 22, 0.08)',
        'warm-lg': '0 10px 30px rgba(159, 60, 22, 0.12)',
      }
    },
  },
  plugins: [],
}
