import { createTranslator } from './src/data/translations';
import { LanguageCode } from './src/types';

const allLanguages: LanguageCode[] = ['hi', 'te', 'ta', 'kn', 'ml', 'mr', 'bn', 'gu', 'pa'];

const requiredKeys = [
  // 1. Landing
  "Welcome to DesiCraft — India's Living Heritage Platform",
  "Preserving 5,000 Years of Indian Craft Heritage",
  "Bridging ancestral Indian GI artisan clusters with conscious global patrons through verifiable digital craft passports and living heritage AI.",
  "Choose your mode to begin:",
  "Patron & Collector Portal",
  "PATRON & COLLECTOR PORTAL",
  "Buyer Marketplace",
  "Sign in to explore products, discover artisans, and purchase traditional crafts.",
  "Authentic GI Handlooms & Crafts",
  "Verifiable Blockchain Digital Craft Passports",
  "Direct Artisan Master Workshops & Apprenticeships",
  "Enter Buyer Marketplace",
  "Artisan & Guild Workspace",
  "ARTISAN & GUILD WORKSPACE",
  "Artisan Studio",
  "Sign in to manage your products, use AI tools, discover opportunities, and collaborate with artisans.",
  "Multilingual Voice Product Creator (10 Languages)",
  "Algorithmic GI Fair Price & Raw Material Advisor",
  "Inter-Craft Synergy & Artisan Collaboration Hub",
  "Enter Artisan Studio",
  "Authentic GI Verified",
  "Heritage Craft Guilds",
  "Indian Languages",
  "Middleman Exploitation",

  // 2. Login
  "Buyer Marketplace • MODE-ENTRY SECURITY GATE",
  "Artisan Studio • MODE-ENTRY SECURITY GATE",
  "Mode-Entry Security Gate",
  "MODE-ENTRY SECURITY GATE",
  "Sign in to access Buyer Marketplace",
  "Sign in to access Artisan Studio",
  "Sign In",
  "Create Account",
  "Email or Phone",
  "EMAIL OR PHONE",
  "Password",
  "PASSWORD",
  "Create Password",
  "Full Name",
  "Checking your session...",
  "Creating Account...",
  "Single Unified DesiCraft Account",
  "Your login credentials work across both Buyer Marketplace and Artisan Studio without duplicate accounts.",
  "QUICK DEMO ACCESS (SINGLE ACCOUNT, DUAL MODE):",
  "Quick Demo Access (Single Account, Dual Mode):",
  "Devi Prasad",
  "Patron / Buyer Account",
  "Master Rajeshwar",
  "Master Artisan Account",
  "Back to Welcome Portal",
  "Back to DesiCraft Home",
  "Please enter your Phone or Email",
  "Please enter your full name",
  "Please enter your email or phone",
  "Password must be at least 6 characters long",
  "Unable to create account. Please try again.",

  // 3. Heritage Map
  "VIBRANT CLUSTERS OF BHARAT",
  "India Handcrafted",
  "Explore the crafts, stories and artisans that make India unique. Hover over any state to reveal its signature masterworks.",
  "Many Crafts • One Bharat",
  "Many Crafts • One Bharat IN",
  "From Himalayan Pashmina to Deccan Ikat and Kutch Block Prints",
  "3D View: ON",
  "3D View: OFF",
  "2D Flat View",
  "700+ Unique Crafts",
  "Unique Crafts",
  "1M+ Living Master Artisans",
  "Living Master Artisans",
  "28 States & 8 UTs",
  "28 States & 8 UTs Geographical Heritage",
  "Geographical Heritage",
  "India's heritage lives in the hands of its people.",
  "“India's heritage lives in the hands of its people.”",
  "Explore • Support • Preserve",
  "EXPLORE • SUPPORT • PRESERVE",
  "INDIAN OCEAN • BHARAT",
  "Famous For:",

  // States
  "Jammu & Kashmir",
  "Himachal Pradesh",
  "Punjab",
  "Haryana",
  "Uttarakhand",
  "Rajasthan",
  "Uttar Pradesh",
  "Gujarat",
  "Madhya Pradesh",
  "Bihar",
  "Jharkhand",
  "West Bengal",
  "Chhattisgarh",
  "Odisha",
  "Maharashtra",
  "Telangana",
  "Andhra Pradesh",
  "Karnataka",
  "Goa",
  "Kerala",
  "Tamil Nadu",
  "Sikkim",
  "Assam",
  "Arunachal Pradesh",
  "Meghalaya",
  "Nagaland",
  "Manipur",
  "Tripura",
  "Mizoram",

  // 4. Products & Crafts
  "Heirloom Kadwa Zari Pure Katan Silk Saree",
  "Telia Rumal Double Ikat Royal Silk Saree",
  "Cosmic Kalpavriksha (Tree of Life) Folk Canvas",
  "Celestial Indigo & Madder 16-Step Ajrakh Dupatta",
  "Palace Arched Cobalt & Turquoise Glazed Urn Vase",
  "Ancient Cire Perdue Tribal Processional Gajraj Elephant",
  "Royal Kani Jamawar 100% Changthangi Pashmina Shawl",
  "Natural Vegetable Lacquer Turned Wood Stacker Toy",

  "Varanasi Zari & Brocade",
  "Pochampally Ikat",
  "Mithila / Madhubani Painting",
  "Kutch Ajrakh Block Print",
  "Jaipur Blue Pottery",
  "Bastar Dhokra Bell Metal",
  "Kashmir Pashmina & Kani Weaving",
  "Channapatna Lacquer Toys",

  "An authentic masterwork handwoven over 48 days on traditional wooden pit looms in Varanasi. Features pure electroplated silver Zari motifs of sacred Kalga peacocks and lotus vines, with zero loose floating threads on the reverse side.",
  "A benchmark of mathematical handweaving precision. Both warp and weft silk yarns are calculated, bundled, and tie-dyed in authentic indigo and alizarin madder before being handwoven on manual tension pit-looms.",
  "An expansive devotional painting depicting the sacred Tree of Life, nesting birds, sun and moon deities, and dancing peacocks. Rendered with fine bamboo twigs and natural organic plant pigments on handmade cotton paper.",
  "Authentic 16-stage resist block-printed stole on lustrous Chanderi silk-cotton. Dyed in living natural indigo vats and Indian madder root, stamped with precision hand-carved Teakwood blocks.",
  "Unique non-clay ceramic decorative urn crafted from mountain quartz powder, recycled glass, and natural gums. Hand-painted with traditional Mughal floral arabesques in rich cobalt and copper oxides.",
  "Heirloom bronze lost-wax cast sculpture made by tribal metallurgists in Kondagaon. Every ornate coil of the saddle and tusks was hand-sculpted in forest beeswax before molten brass was poured into the clay furnace.",
  "An absolute masterpiece of Himalayan craftsmanship. Woven with 100% pure Ladakh Changthangi pashm cashmere (13.5 microns) on a handloom using wooden Kani spools guided by chanted Talim metric verses.",
  "Baby-safe developmental wooden toy turned by hand on woodturning lathes. Polished to a glass-smooth gloss with natural non-toxic plant shellac, turmeric, and vermillion. Safe for toddlers and stunning as shelf decor.",

  "Direct Fair Value",
  "GI Passport",
  "Certified Masterpieces",
  "authentic handcrafted treasures with Digital Craft Passports",
  "DIRECT FROM TRADITIONAL LOOMS",
  "By",
  "ORAL LIVING MEMORY",
  "Listen to Master Artisans in Their Mother Tongue",
  "Hear the sound of the loom and stories passed down through four generations.",
  "Explore Cultural Lineage",
  "High Demand",
  "82% Direct Artisan Wage Guaranteed",
  "Handcraft Technique",
  "Time on Traditional Loom",
  "Digital Craft Passport Attached",
  "Verifiable cryptographic record of master lineage",
  "Inspect Passport",
  "Studio Lighting:",
  "ON (Studio View)",
  "OFF (Raw Loom)",

  "Master Rajeshwar Ansari",
  "Gaddam Lakshmi Devi",
  "Meenakshi Kumari Jha",
  "Dr. Ismail Mohammed Khatri",
  "Mahaveer Prasad Sharma",
  "Somnath Ghadwa",
  "Syed Ghulam Rasool",
  "B. Narayanappa & Sons",
];

for (const lang of allLanguages) {
  const t = createTranslator(lang);
  const untranslated = requiredKeys.filter((k) => t(k) === k);
  console.log(`Language [${lang}]: untranslated ${untranslated.length} / ${requiredKeys.length}`);
  if (untranslated.length > 0) {
    console.log(`  Untranslated examples: ${untranslated.slice(0, 5).join(' | ')}`);
  }
}
